# Generated by Django 4.1 on 2022-08-22 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.service.users.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='product_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), users.service.users.services.validate_size_image])),
                ('first_name', models.CharField(help_text='First name', max_length=32, null=True)),
                ('last_name', models.CharField(help_text='Last name', max_length=32, null=True)),
                ('email', models.EmailField(default='', help_text='Enter a valid email address', max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
