# Generated by Django 4.1 on 2022-08-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('notebook', 'notebook'), ('mobile', 'mobile'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
