# Generated by Django 4.1 on 2022-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('pc', 'pc'), ('mobile', 'mobile'), ('accessories', 'accessories')], default='mobile', max_length=20),
        ),
    ]
