# Generated by Django 4.1 on 2022-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('mobile', 'mobile'), ('notebook', 'notebook'), ('pc', 'pc'), ('accessories', 'accessories')], default='mobile', max_length=20),
        ),
    ]
