# Generated by Django 4.1 on 2022-08-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('mobile', 'mobile'), ('pc', 'pc'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
